# Build Submissions From `inference_eval`

Локальный notebook для сборки `zip`-посылок из уже сохранённых `test_probs_*.pt` и `threshold_sweep_*.csv`.

In [1]:
import json
import hashlib
import zipfile
from pathlib import Path

import numpy as np
import pandas as pd
import torch

In [2]:
ROOT = Path('.')
INFER_DIR = ROOT / 'inference_eval'
TEST_INFO_CSV = ROOT / 'info.csv'
OUT_DIR = ROOT / 'submissions_from_inference_eval'
OUT_DIR.mkdir(parents=True, exist_ok=True)

BEV_H, BEV_W = 188, 126

best_probs_path = INFER_DIR / 'test_probs_best.pt'
ema_probs_candidates = [
    INFER_DIR / 'test_probs_ema_best.pt',
    INFER_DIR / 'test_probs_ema.pt',
]
ema_probs_path = next((p for p in ema_probs_candidates if p.exists()), None)

best_sweep_path = INFER_DIR / 'threshold_sweep_best.csv'
ema_sweep_candidates = [
    INFER_DIR / 'threshold_sweep_ema_best.csv',
    INFER_DIR / 'threshold_sweep_ema.csv',
]
ema_sweep_path = next((p for p in ema_sweep_candidates if p.exists()), None)

assert INFER_DIR.exists(), INFER_DIR
assert TEST_INFO_CSV.exists(), TEST_INFO_CSV
assert best_probs_path.exists(), best_probs_path
assert ema_probs_path is not None, 'No EMA test_probs file found'
assert best_sweep_path.exists(), best_sweep_path
assert ema_sweep_path is not None, 'No EMA threshold_sweep csv found'

print('best_probs_path:', best_probs_path)
print('ema_probs_path:', ema_probs_path)
print('best_sweep_path:', best_sweep_path)
print('ema_sweep_path:', ema_sweep_path)
print('test_info:', TEST_INFO_CSV)
print('out_dir:', OUT_DIR)

best_probs_path: inference_eval/test_probs_best.pt
ema_probs_path: inference_eval/test_probs_ema.pt
best_sweep_path: inference_eval/threshold_sweep_best.csv
ema_sweep_path: inference_eval/threshold_sweep_ema_best.csv
test_info: info.csv
out_dir: submissions_from_inference_eval

In [3]:
test_info = pd.read_csv(TEST_INFO_CSV, index_col=0).reset_index(drop=True)
print('test rows:', len(test_info))
display(test_info.head())

best_sweep = pd.read_csv(best_sweep_path)
ema_sweep = pd.read_csv(ema_sweep_path)

display(best_sweep.sort_values('iou', ascending=False).head(10))
display(ema_sweep.sort_values('iou', ascending=False).head(10))

test rows: 2000

,gt_occupancy_grid,header_ts,log_time,message_ts,/camera/inner/frontal/middle,/side/left/forward,/side/right/forward,/camera/inner/frontal/far,/camera/inner/frontal/middle/intrinsic_params,/camera/inner/frontal/middle/car_to_cam,...,/side/left/forward/car_to_cam,/side/right/forward/intrinsic_params,/side/right/forward/car_to_cam,/camera/inner/frontal/far/intrinsic_params,/camera/inner/frontal/far/car_to_cam,predicted_occupancy_grid,ride_date,ride_time,rover,scene_part_order
0,autonomy_yandex_dataset_test/static_grids/1706...,1706096985200039000,14:22:32,1706096985200039000,autonomy_yandex_dataset_test/images/1706096985...,autonomy_yandex_dataset_test/images/1706096985...,autonomy_yandex_dataset_test/images/1706096985...,autonomy_yandex_dataset_test/images/1706096985...,autonomy_yandex_dataset_test/matrices/17060969...,autonomy_yandex_dataset_test/matrices/17060969...,...,autonomy_yandex_dataset_test/matrices/17060969...,autonomy_yandex_dataset_test/matrices/17060969...,autonomy_yandex_dataset_test/matrices/17060969...,autonomy_yandex_dataset_test/matrices/17060969...,autonomy_yandex_dataset_test/matrices/17060969...,autonomy_yandex_dataset_test/predicted_static_...,2024-01-24,13:21:16,natelio,0
1,autonomy_yandex_dataset_test/static_grids/1706...,1706097249999986000,14:22:32,1706097249999986000,autonomy_yandex_dataset_test/images/1706097249...,autonomy_yandex_dataset_test/images/1706097249...,autonomy_yandex_dataset_test/images/1706097249...,autonomy_yandex_dataset_test/images/1706097249...,autonomy_yandex_dataset_test/matrices/17060972...,autonomy_yandex_dataset_test/matrices/17060972...,...,autonomy_yandex_dataset_test/matrices/17060972...,autonomy_yandex_dataset_test/matrices/17060972...,autonomy_yandex_dataset_test/matrices/17060972...,autonomy_yandex_dataset_test/matrices/17060972...,autonomy_yandex_dataset_test/matrices/17060972...,autonomy_yandex_dataset_test/predicted_static_...,2024-01-24,13:21:16,natelio,0
2,autonomy_yandex_dataset_test/static_grids/1715...,1715156441999867000,11:16:12,1715156441999867000,autonomy_yandex_dataset_test/images/1715156441...,autonomy_yandex_dataset_test/images/1715156441...,autonomy_yandex_dataset_test/images/1715156441...,autonomy_yandex_dataset_test/images/1715156441...,autonomy_yandex_dataset_test/matrices/17151564...,autonomy_yandex_dataset_test/matrices/17151564...,...,autonomy_yandex_dataset_test/matrices/17151564...,autonomy_yandex_dataset_test/matrices/17151564...,autonomy_yandex_dataset_test/matrices/17151564...,autonomy_yandex_dataset_test/matrices/17151564...,autonomy_yandex_dataset_test/matrices/17151564...,autonomy_yandex_dataset_test/predicted_static_...,2024-05-08,11:16:12,hetera,0
3,autonomy_yandex_dataset_test/static_grids/1715...,1715161824799910000,12:43:44,1715161824799910000,autonomy_yandex_dataset_test/images/1715161824...,autonomy_yandex_dataset_test/images/1715161824...,autonomy_yandex_dataset_test/images/1715161824...,autonomy_yandex_dataset_test/images/1715161824...,autonomy_yandex_dataset_test/matrices/17151618...,autonomy_yandex_dataset_test/matrices/17151618...,...,autonomy_yandex_dataset_test/matrices/17151618...,autonomy_yandex_dataset_test/matrices/17151618...,autonomy_yandex_dataset_test/matrices/17151618...,autonomy_yandex_dataset_test/matrices/17151618...,autonomy_yandex_dataset_test/matrices/17151618...,autonomy_yandex_dataset_test/predicted_static_...,2024-05-08,12:43:44,natelio,0
4,autonomy_yandex_dataset_test/static_grids/1717...,1717418724299998000,15:34:54,1717418724299998000,autonomy_yandex_dataset_test/images/1717418724...,autonomy_yandex_dataset_test/images/1717418724...,autonomy_yandex_dataset_test/images/1717418724...,autonomy_yandex_dataset_test/images/1717418724...,autonomy_yandex_dataset_test/matrices/17174187...,autonomy_yandex_dataset_test/matrices/17174187...,...,autonomy_yandex_dataset_test/matrices/17174187...,autonomy_yandex_dataset_test/matrices/17174187...,autonomy_yandex_dataset_test/matrices/17174187...,autonomy_yandex_dataset_test/matrices/17174187...,autonomy_yandex_dataset_test/matrices/17174187...,autonomy_yandex_dataset_test/predicted_static_...,2024-06-03,15:34:54,arlim,0

    threshold       iou
18       0.56  0.604716
17       0.54  0.604621
16       0.52  0.604319
19       0.58  0.604288
15       0.50  0.603915
20       0.60  0.603556
14       0.48  0.603257
21       0.62  0.602884
13       0.46  0.602670
12       0.44  0.601924

    threshold       iou
17       0.54  0.603734
18       0.56  0.603562
16       0.52  0.603548
15       0.50  0.603219
19       0.58  0.603209
20       0.60  0.602735
14       0.48  0.602664
13       0.46  0.601951
21       0.62  0.601497
12       0.44  0.601072

In [4]:
def best_threshold_from_sweep(df: pd.DataFrame) -> float:
    row = df.sort_values(['iou', 'threshold'], ascending=[False, True]).iloc[0]
    return float(row['threshold'])


best_t_best = best_threshold_from_sweep(best_sweep)
best_t_ema = best_threshold_from_sweep(ema_sweep)

print('best threshold for best:', best_t_best)
print('best threshold for ema:', best_t_ema)

best threshold for best: 0.56
best threshold for ema: 0.54

In [5]:
def load_probs(path: Path) -> torch.Tensor:
    obj = torch.load(path, map_location='cpu')
    if isinstance(obj, dict) and 'probs' in obj:
        obj = obj['probs']
    if isinstance(obj, np.ndarray):
        obj = torch.from_numpy(obj)
    if not isinstance(obj, torch.Tensor):
        raise TypeError(f'Unexpected probs type: {type(obj)}')
    return obj.float()


best_probs = load_probs(best_probs_path)
ema_probs = load_probs(ema_probs_path)

print('best_probs shape:', tuple(best_probs.shape))
print('ema_probs shape:', tuple(ema_probs.shape))
assert len(best_probs) == len(test_info), (len(best_probs), len(test_info))
assert len(ema_probs) == len(test_info), (len(ema_probs), len(test_info))

best_probs shape: (2000, 1, 188, 126)
ema_probs shape: (2000, 1, 188, 126)

In [6]:
def pred_name_from_row(row):
    if 'predicted_occupancy_grid' in row:
        return Path(row['predicted_occupancy_grid']).name
    if 'predicted_static_grid' in row:
        return Path(row['predicted_static_grid']).name
    return f'{int(row.name)}.npy'

import functools
from src.submission import make_submission_from_probs as _make_submission_from_probs
make_submission_from_probs = functools.partial(
    _make_submission_from_probs,
    out_root=OUT_DIR, test_info=test_info,
    info_csv=TEST_INFO_CSV, pred_name_fn=pred_name_from_row,
)

In [ ]:
best_thresholds = sorted(set([0.745, 0.75, 0.755, 0.765, 0.77, 0.775]))
best_thresholds = [t for t in best_thresholds if 0.05 <= t <= 0.95]

ema_thresholds = sorted(set([0.5, 0.52, 0.54, 0.56, 0.58, 0.6, 0.62, 0.64, 0.66, 0.68, 0.7, 0.72, 0.74, 0.76, 0.78, 0.8, 0.82, 0.84, 0.86, 0.88]))
ema_thresholds = [t for t in ema_thresholds if 0.05 <= t <= 0.95]

print('best_thresholds:', best_thresholds)
print('ema_thresholds:', ema_thresholds)

best_thresholds: [0.5, 0.52, 0.54, 0.56, 0.58, 0.6, 0.62, 0.64, 0.66, 0.68, 0.7, 0.72, 0.74, 0.76, 0.78, 0.8, 0.82, 0.84, 0.86, 0.88]
ema_thresholds: [0.5, 0.52, 0.54, 0.56, 0.58, 0.6, 0.62, 0.64, 0.66, 0.68, 0.7, 0.72, 0.74, 0.76, 0.78, 0.8, 0.82, 0.84, 0.86, 0.88]

In [9]:
submission_results = []

for t in best_thresholds:
    print('\n' + '=' * 100)
    print(f'building BEST submission for threshold={t:.2f}')
    submission_results.append(make_submission_from_probs(best_probs, t, 'best'))

for t in ema_thresholds:
    print('\n' + '=' * 100)
    print(f'building EMA submission for threshold={t:.2f}')
    submission_results.append(make_submission_from_probs(ema_probs, t, 'ema'))

submission_results_df = pd.DataFrame(submission_results)
display(submission_results_df)

====================================================================================================
building BEST submission for threshold=0.50
{
  "model_tag": "best",
  "threshold": 0.5,
  "zip_path": "/Users/r-shangareev/PyProjects/shine-time/ML2_2026_Competition/submissions_from_inference_eval/submission_best_t_0p50.zip",
  "size_mb": 2.684,
  "sha256": "ffcd82abaa797675ebed9e2f9f460188b39e2677a790dc97df6f217aff0d7981"
}

====================================================================================================
building BEST submission for threshold=0.52
{
  "model_tag": "best",
  "threshold": 0.52,
  "zip_path": "/Users/r-shangareev/PyProjects/shine-time/ML2_2026_Competition/submissions_from_inference_eval/submission_best_t_0p52.zip",
  "size_mb": 2.729,
  "sha256": "f26a9d5c137acb651cdb7ab559b9f5bbc7765ece6c2b688ab402c057054b9a07"
}

====================================================================================================
building BEST submission for threshold=0.54
{
  "model_tag": "best",
  "threshold": 0.54,
  "zip_path": "/Users/r-shangareev/PyProjects/shine-time/ML2_2026_Competition/submissions_from_inference_eval/submission_best_t_0p54.zip",
  "size_mb": 2.777,
  "sha256": "2f96dc34531a1e20edaa41645a2efd27ef0fd5e351ee226c3ce8ee3616a7fe26"
}

====================================================================================================
building BEST submission for threshold=0.56
{
  "model_tag": "best",
  "threshold": 0.56,
  "zip_path": "/Users/r-shangareev/PyProjects/shine-time/ML2_2026_Competition/submissions_from_inference_eval/submission_best_t_0p56.zip",
  "size_mb": 2.83,
  "sha256": "5e284dc47a3b6ea5cf0c2667757b68771eb9862525253b116e507fa612f549ce"
}

====================================================================================================
building BEST submission for threshold=0.58
{
  "model_tag": "best",
  "threshold": 0.58,
  "zip_path": "/Users/r-shangareev/PyProjects/shine-time/ML2_2026_Competition/submissions_from_inference_eval/submission_best_t_0p58.zip",
  "size_mb": 2.883,
  "sha256": "55e41bbf5c5c84b64e6b7f1fda60df8bcd0e5cdfcc58abc467ee9c6ed823194c"
}

====================================================================================================
building BEST submission for threshold=0.60
{
  "model_tag": "best",
  "threshold": 0.6,
  "zip_path": "/Users/r-shangareev/PyProjects/shine-time/ML2_2026_Competition/submissions_from_inference_eval/submission_best_t_0p60.zip",
  "size_mb": 2.938,
  "sha256": "334c85a5fb0200ec6a722f22ec15d19e3a24af63a2148537c4ea48e61a5b06f3"
}

====================================================================================================
building BEST submission for threshold=0.62
{
  "model_tag": "best",
  "threshold": 0.62,
  "zip_path": "/Users/r-shangareev/PyProjects/shine-time/ML2_2026_Competition/submissions_from_inference_eval/submission_best_t_0p62.zip",
  "size_mb": 3.001,
  "sha256": "8c01bd0925bac527951f08a67f76e3408898db4dc27c06263609f0f277505f59"
}

====================================================================================================
building BEST submission for threshold=0.64
{
  "model_tag": "best",
  "threshold": 0.64,
  "zip_path": "/Users/r-shangareev/PyProjects/shine-time/ML2_2026_Competition/submissions_from_inference_eval/submission_best_t_0p64.zip",
  "size_mb": 3.063,
  "sha256": "564b6a921a5e5c9ad442df9cbda4fff5f3f2cfb233a64240c090ac910f835d07"
}

====================================================================================================
building BEST submission for threshold=0.66
{
  "model_tag": "best",
  "threshold": 0.66,
  "zip_path": "/Users/r-shangareev/PyProjects/shine-time/ML2_2026_Competition/submissions_from_inference_eval/submission_best_t_0p66.zip",
  "size_mb": 3.125,
  "sha256": "ccecba0a091cbc2dc33d938bdcd0b8798af15607c29e7f2bd192ba1d2014fc86"
}

====================================================================================================
building BEST submission for threshold=0.68
{
  "model_tag": "best",
  "threshold": 0.68,
  "zip_path": "/Users/r-shangareev/PyProjects/shine-time/ML2_2026_Competition/submissions_from_inference_eval/submission_best_t_0p68.zip",
  "size_mb": 3.185,
  "sha256": "cb28bcde01fbba756e11bbcccbf300b662254016873b2716da8520f555524bbf"
}

====================================================================================================
building BEST submission for threshold=0.70
{
  "model_tag": "best",
  "threshold": 0.7,
  "zip_path": "/Users/r-shangareev/PyProjects/shine-time/ML2_2026_Competition/submissions_from_inference_eval/submission_best_t_0p70.zip",
  "size_mb": 3.244,
  "sha256": "fc1beef3cf5b2f8c88d8220ae5102469aca943f31cadd67f9a763809268faffb"
}

====================================================================================================
building BEST submission for threshold=0.72
{
  "model_tag": "best",
  "threshold": 0.72,
  "zip_path": "/Users/r-shangareev/PyProjects/shine-time/ML2_2026_Competition/submissions_from_inference_eval/submission_best_t_0p72.zip",
  "size_mb": 3.3,
  "sha256": "8e5ba65575fe5c5186933187ae4d7a14c5602c280e7086a7baf56411fa3517c4"
}

====================================================================================================
building BEST submission for threshold=0.74
{
  "model_tag": "best",
  "threshold": 0.74,
  "zip_path": "/Users/r-shangareev/PyProjects/shine-time/ML2_2026_Competition/submissions_from_inference_eval/submission_best_t_0p74.zip",
  "size_mb": 3.346,
  "sha256": "3cad350114ee0889a4117d6d9c2c07e96afae8fc05e1d12f358ba3bcbb28986c"
}

====================================================================================================
building BEST submission for threshold=0.76
{
  "model_tag": "best",
  "threshold": 0.76,
  "zip_path": "/Users/r-shangareev/PyProjects/shine-time/ML2_2026_Competition/submissions_from_inference_eval/submission_best_t_0p76.zip",
  "size_mb": 3.38,
  "sha256": "76412da594ecd78a9c5c909c107a763f1b0602a389cd19ecf8c9ebddd00b7329"
}

====================================================================================================
building BEST submission for threshold=0.78
{
  "model_tag": "best",
  "threshold": 0.78,
  "zip_path": "/Users/r-shangareev/PyProjects/shine-time/ML2_2026_Competition/submissions_from_inference_eval/submission_best_t_0p78.zip",
  "size_mb": 3.403,
  "sha256": "d1457ee519b5a65392889f9c0acca9e54281977b4008da2527736ae9d4785e51"
}

====================================================================================================
building BEST submission for threshold=0.80
{
  "model_tag": "best",
  "threshold": 0.8,
  "zip_path": "/Users/r-shangareev/PyProjects/shine-time/ML2_2026_Competition/submissions_from_inference_eval/submission_best_t_0p80.zip",
  "size_mb": 3.41,
  "sha256": "44a592b0c87f4102a9c6f0dd7c4a543637405cd865251014199b09e97ca0716b"
}

====================================================================================================
building BEST submission for threshold=0.82
{
  "model_tag": "best",
  "threshold": 0.82,
  "zip_path": "/Users/r-shangareev/PyProjects/shine-time/ML2_2026_Competition/submissions_from_inference_eval/submission_best_t_0p82.zip",
  "size_mb": 3.391,
  "sha256": "d106313f7969fdcf5ac1c71689328b380280f3a80cd9d6490dfbacf3b7c82668"
}

====================================================================================================
building BEST submission for threshold=0.84
{
  "model_tag": "best",
  "threshold": 0.84,
  "zip_path": "/Users/r-shangareev/PyProjects/shine-time/ML2_2026_Competition/submissions_from_inference_eval/submission_best_t_0p84.zip",
  "size_mb": 3.352,
  "sha256": "b2ce86d8e0d3fb798f36bc0dcb9b76260f02b280c398f37978501848a9c7ca90"
}

====================================================================================================
building BEST submission for threshold=0.86
{
  "model_tag": "best",
  "threshold": 0.86,
  "zip_path": "/Users/r-shangareev/PyProjects/shine-time/ML2_2026_Competition/submissions_from_inference_eval/submission_best_t_0p86.zip",
  "size_mb": 3.278,
  "sha256": "4d2c49f52a73c0ee4a1bfebd33177f8923a6b01911ecaa68e435d87011564a37"
}

====================================================================================================
building BEST submission for threshold=0.88
{
  "model_tag": "best",
  "threshold": 0.88,
  "zip_path": "/Users/r-shangareev/PyProjects/shine-time/ML2_2026_Competition/submissions_from_inference_eval/submission_best_t_0p88.zip",
  "size_mb": 3.172,
  "sha256": "c4ecc34f714737594a378db43e54946612aba2d42e31543ec6177d2861673ba8"
}

====================================================================================================
building EMA submission for threshold=0.50
{
  "model_tag": "ema",
  "threshold": 0.5,
  "zip_path": "/Users/r-shangareev/PyProjects/shine-time/ML2_2026_Competition/submissions_from_inference_eval/submission_ema_t_0p50.zip",
  "size_mb": 2.714,
  "sha256": "b188848ca850387e09a377df49d916a9e649b25166cd1bb0344e1e85f9739ad4"
}

====================================================================================================
building EMA submission for threshold=0.52
{
  "model_tag": "ema",
  "threshold": 0.52,
  "zip_path": "/Users/r-shangareev/PyProjects/shine-time/ML2_2026_Competition/submissions_from_inference_eval/submission_ema_t_0p52.zip",
  "size_mb": 2.76,
  "sha256": "20932c486f4563138e482d871344bfd4ba077d75c0f8d1e10f690b04c92899b2"
}

====================================================================================================
building EMA submission for threshold=0.54
{
  "model_tag": "ema",
  "threshold": 0.54,
  "zip_path": "/Users/r-shangareev/PyProjects/shine-time/ML2_2026_Competition/submissions_from_inference_eval/submission_ema_t_0p54.zip",
  "size_mb": 2.811,
  "sha256": "4b59cd9ec4dfcadee1480abb56fe36db441cdd81133588f16d0cdd40d3d10fba"
}

====================================================================================================
building EMA submission for threshold=0.56
{
  "model_tag": "ema",
  "threshold": 0.56,
  "zip_path": "/Users/r-shangareev/PyProjects/shine-time/ML2_2026_Competition/submissions_from_inference_eval/submission_ema_t_0p56.zip",
  "size_mb": 2.868,
  "sha256": "4397dc87276b7fc2534aa05944c265aad533ba5cccac58736d3258c5d44db037"
}

====================================================================================================
building EMA submission for threshold=0.58
{
  "model_tag": "ema",
  "threshold": 0.58,
  "zip_path": "/Users/r-shangareev/PyProjects/shine-time/ML2_2026_Competition/submissions_from_inference_eval/submission_ema_t_0p58.zip",
  "size_mb": 2.925,
  "sha256": "cfc0b694334ee7dd19c876d7716688d1a3e3e44c5152f73295f0b07bda4c6ac8"
}

====================================================================================================
building EMA submission for threshold=0.60
{
  "model_tag": "ema",
  "threshold": 0.6,
  "zip_path": "/Users/r-shangareev/PyProjects/shine-time/ML2_2026_Competition/submissions_from_inference_eval/submission_ema_t_0p60.zip",
  "size_mb": 2.988,
  "sha256": "667a0826edd23335b61da564a87b7a23012c24e0d2e6a1f9e265bc08abcb42a5"
}

====================================================================================================
building EMA submission for threshold=0.62
{
  "model_tag": "ema",
  "threshold": 0.62,
  "zip_path": "/Users/r-shangareev/PyProjects/shine-time/ML2_2026_Competition/submissions_from_inference_eval/submission_ema_t_0p62.zip",
  "size_mb": 3.048,
  "sha256": "f7adef102c4981b979fb4c98973cd4827689d6b094299b5a2c8a13feea8e7a72"
}

====================================================================================================
building EMA submission for threshold=0.64
{
  "model_tag": "ema",
  "threshold": 0.64,
  "zip_path": "/Users/r-shangareev/PyProjects/shine-time/ML2_2026_Competition/submissions_from_inference_eval/submission_ema_t_0p64.zip",
  "size_mb": 3.116,
  "sha256": "1e05e7a062697c66c62f3f8173dff2fc8e5eaa07c793a94d1e5536c21c67eba9"
}

====================================================================================================
building EMA submission for threshold=0.66
{
  "model_tag": "ema",
  "threshold": 0.66,
  "zip_path": "/Users/r-shangareev/PyProjects/shine-time/ML2_2026_Competition/submissions_from_inference_eval/submission_ema_t_0p66.zip",
  "size_mb": 3.179,
  "sha256": "b26aa1e4e010b8e24a591cb9a4eb233b8852218f07e74b5f9f48c83985180ff3"
}

====================================================================================================
building EMA submission for threshold=0.68
{
  "model_tag": "ema",
  "threshold": 0.68,
  "zip_path": "/Users/r-shangareev/PyProjects/shine-time/ML2_2026_Competition/submissions_from_inference_eval/submission_ema_t_0p68.zip",
  "size_mb": 3.243,
  "sha256": "b42abd5bb85cba723955fdd9bd622b8cae02658449c1da6238e240e2847cd326"
}

====================================================================================================
building EMA submission for threshold=0.70
{
  "model_tag": "ema",
  "threshold": 0.7,
  "zip_path": "/Users/r-shangareev/PyProjects/shine-time/ML2_2026_Competition/submissions_from_inference_eval/submission_ema_t_0p70.zip",
  "size_mb": 3.303,
  "sha256": "16cf65bfc2ed88e3380f71788d7655b2b4cae3927faf1dd81192fcb9eb97e21d"
}

====================================================================================================
building EMA submission for threshold=0.72
{
  "model_tag": "ema",
  "threshold": 0.72,
  "zip_path": "/Users/r-shangareev/PyProjects/shine-time/ML2_2026_Competition/submissions_from_inference_eval/submission_ema_t_0p72.zip",
  "size_mb": 3.356,
  "sha256": "aad8381b7198eaa13c6c15ec705cab81e6e6588e80355b883c40796bdb1fab5b"
}

====================================================================================================
building EMA submission for threshold=0.74
{
  "model_tag": "ema",
  "threshold": 0.74,
  "zip_path": "/Users/r-shangareev/PyProjects/shine-time/ML2_2026_Competition/submissions_from_inference_eval/submission_ema_t_0p74.zip",
  "size_mb": 3.402,
  "sha256": "6e2e78f8b0d24aa9ec434d31a25ebb3219300078493e354500580bedd14f6d62"
}

====================================================================================================
building EMA submission for threshold=0.76
{
  "model_tag": "ema",
  "threshold": 0.76,
  "zip_path": "/Users/r-shangareev/PyProjects/shine-time/ML2_2026_Competition/submissions_from_inference_eval/submission_ema_t_0p76.zip",
  "size_mb": 3.432,
  "sha256": "85aa9d5f4fc672fb14bd870e9c4826004aac421b0bac43b7594ee2cae35c24f9"
}

====================================================================================================
building EMA submission for threshold=0.78
{
  "model_tag": "ema",
  "threshold": 0.78,
  "zip_path": "/Users/r-shangareev/PyProjects/shine-time/ML2_2026_Competition/submissions_from_inference_eval/submission_ema_t_0p78.zip",
  "size_mb": 3.453,
  "sha256": "8e980d3b0b10f7aaa9e4c42c5cf36e939ba5708c6d16a5b69e9511cb7d607ec4"
}

====================================================================================================
building EMA submission for threshold=0.80
{
  "model_tag": "ema",
  "threshold": 0.8,
  "zip_path": "/Users/r-shangareev/PyProjects/shine-time/ML2_2026_Competition/submissions_from_inference_eval/submission_ema_t_0p80.zip",
  "size_mb": 3.449,
  "sha256": "05be214ef309541bd2fa5bbc57a57a66147234a74e1ac2fe110ae5acc0e337a1"
}

====================================================================================================
building EMA submission for threshold=0.82
{
  "model_tag": "ema",
  "threshold": 0.82,
  "zip_path": "/Users/r-shangareev/PyProjects/shine-time/ML2_2026_Competition/submissions_from_inference_eval/submission_ema_t_0p82.zip",
  "size_mb": 3.423,
  "sha256": "79eb4c9b9e8039c132d22cea943566a91e1fa1ea792512c4eeafc17208df29db"
}

====================================================================================================
building EMA submission for threshold=0.84
{
  "model_tag": "ema",
  "threshold": 0.84,
  "zip_path": "/Users/r-shangareev/PyProjects/shine-time/ML2_2026_Competition/submissions_from_inference_eval/submission_ema_t_0p84.zip",
  "size_mb": 3.371,
  "sha256": "07b0475f39fe36f4bd6cb05e79ffc5029772343d1801783a3fe343700faef597"
}

====================================================================================================
building EMA submission for threshold=0.86
{
  "model_tag": "ema",
  "threshold": 0.86,
  "zip_path": "/Users/r-shangareev/PyProjects/shine-time/ML2_2026_Competition/submissions_from_inference_eval/submission_ema_t_0p86.zip",
  "size_mb": 3.286,
  "sha256": "dac599298f189a09be8f29dd1c28d5ffb1981cc63757a8c898e5ef57a75c3f23"
}

====================================================================================================
building EMA submission for threshold=0.88
{
  "model_tag": "ema",
  "threshold": 0.88,
  "zip_path": "/Users/r-shangareev/PyProjects/shine-time/ML2_2026_Competition/submissions_from_inference_eval/submission_ema_t_0p88.zip",
  "size_mb": 3.166,
  "sha256": "7d3fc147753587aec50309b2cce28119a0ad79dab92af077da244f73f09c538b"
}

,model_tag,threshold,zip_path,size_mb,sha256
0,best,0.50,/Users/r-shangareev/PyProjects/shine-time/ML2_...,2.684,ffcd82abaa797675ebed9e2f9f460188b39e2677a790dc...
1,best,0.52,/Users/r-shangareev/PyProjects/shine-time/ML2_...,2.729,f26a9d5c137acb651cdb7ab559b9f5bbc7765ece6c2b68...
2,best,0.54,/Users/r-shangareev/PyProjects/shine-time/ML2_...,2.777,2f96dc34531a1e20edaa41645a2efd27ef0fd5e351ee22...
3,best,0.56,/Users/r-shangareev/PyProjects/shine-time/ML2_...,2.830,5e284dc47a3b6ea5cf0c2667757b68771eb9862525253b...
4,best,0.58,/Users/r-shangareev/PyProjects/shine-time/ML2_...,2.883,55e41bbf5c5c84b64e6b7f1fda60df8bcd0e5cdfcc58ab...
5,best,0.60,/Users/r-shangareev/PyProjects/shine-time/ML2_...,2.938,334c85a5fb0200ec6a722f22ec15d19e3a24af63a21485...
6,best,0.62,/Users/r-shangareev/PyProjects/shine-time/ML2_...,3.001,8c01bd0925bac527951f08a67f76e3408898db4dc27c06...
7,best,0.64,/Users/r-shangareev/PyProjects/shine-time/ML2_...,3.063,564b6a921a5e5c9ad442df9cbda4fff5f3f2cfb233a642...
8,best,0.66,/Users/r-shangareev/PyProjects/shine-time/ML2_...,3.125,ccecba0a091cbc2dc33d938bdcd0b8798af15607c29e7f...
9,best,0.68,/Users/r-shangareev/PyProjects/shine-time/ML2_...,3.185,cb28bcde01fbba756e11bbcccbf300b662254016873b27...
10,best,0.70,/Users/r-shangareev/PyProjects/shine-time/ML2_...,3.244,fc1beef3cf5b2f8c88d8220ae5102469aca943f31cadd6...
11,best,0.72,/Users/r-shangareev/PyProjects/shine-time/ML2_...,3.300,8e5ba65575fe5c5186933187ae4d7a14c5602c280e7086...
12,best,0.74,/Users/r-shangareev/PyProjects/shine-time/ML2_...,3.346,3cad350114ee0889a4117d6d9c2c07e96afae8fc05e1d1...
13,best,0.76,/Users/r-shangareev/PyProjects/shine-time/ML2_...,3.380,76412da594ecd78a9c5c909c107a763f1b0602a389cd19...
14,best,0.78,/Users/r-shangareev/PyProjects/shine-time/ML2_...,3.403,d1457ee519b5a65392889f9c0acca9e54281977b4008da...
15,best,0.80,/Users/r-shangareev/PyProjects/shine-time/ML2_...,3.410,44a592b0c87f4102a9c6f0dd7c4a543637405cd8652510...
16,best,0.82,/Users/r-shangareev/PyProjects/shine-time/ML2_...,3.391,d106313f7969fdcf5ac1c71689328b380280f3a80cd9d6...
17,best,0.84,/Users/r-shangareev/PyProjects/shine-time/ML2_...,3.352,b2ce86d8e0d3fb798f36bc0dcb9b76260f02b280c398f3...
18,best,0.86,/Users/r-shangareev/PyProjects/shine-time/ML2_...,3.278,4d2c49f52a73c0ee4a1bfebd33177f8923a6b01911ecaa...
19,best,0.88,/Users/r-shangareev/PyProjects/shine-time/ML2_...,3.172,c4ecc34f714737594a378db43e54946612aba2d42e3154...
20,ema,0.50,/Users/r-shangareev/PyProjects/shine-time/ML2_...,2.714,b188848ca850387e09a377df49d916a9e649b25166cd1b...
21,ema,0.52,/Users/r-shangareev/PyProjects/shine-time/ML2_...,2.760,20932c486f4563138e482d871344bfd4ba077d75c0f8d1...
22,ema,0.54,/Users/r-shangareev/PyProjects/shine-time/ML2_...,2.811,4b59cd9ec4dfcadee1480abb56fe36db441cdd81133588...
23,ema,0.56,/Users/r-shangareev/PyProjects/shine-time/ML2_...,2.868,4397dc87276b7fc2534aa05944c265aad533ba5cccac58...
24,ema,0.58,/Users/r-shangareev/PyProjects/shine-time/ML2_...,2.925,cfc0b694334ee7dd19c876d7716688d1a3e3e44c5152f7...
25,ema,0.60,/Users/r-shangareev/PyProjects/shine-time/ML2_...,2.988,667a0826edd23335b61da564a87b7a23012c24e0d2e6a1...
26,ema,0.62,/Users/r-shangareev/PyProjects/shine-time/ML2_...,3.048,f7adef102c4981b979fb4c98973cd4827689d6b094299b...
27,ema,0.64,/Users/r-shangareev/PyProjects/shine-time/ML2_...,3.116,1e05e7a062697c66c62f3f8173dff2fc8e5eaa07c793a9...
28,ema,0.66,/Users/r-shangareev/PyProjects/shine-time/ML2_...,3.179,b26aa1e4e010b8e24a591cb9a4eb233b8852218f07e74b...
29,ema,0.68,/Users/r-shangareev/PyProjects/shine-time/ML2_...,3.243,b42abd5bb85cba723955fdd9bd622b8cae02658449c1da...
30,ema,0.70,/Users/r-shangareev/PyProjects/shine-time/ML2_...,3.303,16cf65bfc2ed88e3380f71788d7655b2b4cae3927faf1d...
31,ema,0.72,/Users/r-shangareev/PyProjects/shine-time/ML2_...,3.356,aad8381b7198eaa13c6c15ec705cab81e6e6588e80355b...
32,ema,0.74,/Users/r-shangareev/PyProjects/shine-time/ML2_...,3.402,6e2e78f8b0d24aa9ec434d31a25ebb3219300078493e35...
33,ema,0.76,/Users/r-shangareev/PyProjects/shine-time/ML2_...,3.432,85aa9d5f4fc672fb14bd870e9c4826004aac421b0bac43...
34,ema,0.78,/Users/r-shangareev/PyProjects/shine-time/ML2_...,3.453,8e980d3b0b10f7aaa9e4c42c5cf36e939ba5708c6d16a5...
35,ema,0.80,/Users/r-shangareev/PyProjects/shine-time/ML2_...,3.449,05be214ef309541bd2fa5bbc57a57a66147234a74e1ac2...
36,ema,0.82,/Users/r-shangareev/PyProjects/shine-time/ML2_...,3.423,79eb4c9b9e8039c132d22cea943566a91e1fa1ea792512...
37,ema,0.84,/Users/r-shangareev/PyProjects/shine-time/ML2_...,3.371,07b0475f39fe36f4bd6cb05e79ffc5029772343d180178...
38,ema,0.86,/Users/r-shangareev/PyProjects/shine-time/ML2_...,3.286,dac599298f189a09be8f29dd1c28d5ffb1981cc63757a8...
39,ema,0.88,/Users/r-shangareev/PyProjects/shine-time/ML2_...,3.166,7d3fc147753587aec50309b2cce28119a0ad79dab92af0...

In [ ]:
bundle_path = OUT_DIR / 'all_submissions_bundle.zip'
if bundle_path.exists():
    bundle_path.unlink()

with zipfile.ZipFile(bundle_path, 'w', compression=zipfile.ZIP_DEFLATED, compresslevel=6) as zf:
    manifest = []
    for row in submission_results:
        p = Path(row['zip_path'])
        zf.write(p, arcname=p.name)
        manifest.append(row)
    zf.writestr('manifest.json', json.dumps(manifest, indent=2, ensure_ascii=False))

print('bundle:', bundle_path)
print('bundle size_mb:', round(bundle_path.stat().st_size / 1e6, 3))